version: "3.9"

services:
  db:
    image: postgres:15.2
    restart: unless-stopped
    environment:
      POSTGRES_PASSWORD: Dev123!
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - "./postgres:/docker-entrypoint-initdb.d/"
    ports:
      - "5432:5432"
  api:
    depends_on: ['db', 'rabbit']
    build: ..
    restart: unless-stopped
    environment:
      POSTGRES_USER: identify
      POSTGRES_PASS: Dev123!
      POSTGRES_URL: "jdbc:postgresql://db:5432/identify"
    command: "java -Duser.dir=/identify/ -jar /identify/IdentifyAPI-0.0.1-SNAPSHOT.war"
    volumes:
      - keyfiles:/identify/keys
    ports:
      - "8080:8080"
      - "5005:5005"
  rabbit:
    image: rabbitmq:management
    volumes:
      - ./rabbitmq/rabbitmq.conf:/etc/rabbitmq/rabbitmq.conf
      - ./rabbitmq/enabled_plugins:/etc/rabbitmq/enabled_plugins
    ports:
      - "15672:15672"
      - "1883:1883"
      - "5672:5672"

volumes:
  postgres_data:
  keyfiles:
